spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/delivery_db
    username: postgresql
    password: admin
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
